#!/bin/sh

# Uninstall script for SifDec

# syntax: uninstall_sifdec

# N. Gould, D. Orban & Ph. Toint
# ( Last modified on Wed Aug  3 12:05:39 EDT 2005 )

cur=$PWD
$cur/bin/uninstall_sifdec.sh

#if [ -x /bin/bash ]
#then
#  echo "Uninstalling in the Bourne Again shell"
#  $cur/bin/uninstall_sifdec.sh
#elif [ -x /bin/csh || -x /bin/tcsh ]
#then
#  echo "Uninstalling in the C shell"
#  $cur/bin/uninstall_sifdec.csh
#else
#  echo "Could not find bash or (t)csh"
#  exit 1
#fi
