# Example yaml configuration file for the legacy implementation
# All relevant input is in one file with two sections: SYSTEM and SETTINGS

# Start of yaml document
---
###############################################################################
# SECTION 1 : SYSTEM
# Define the physical system (e.g. the galaxy or globular cluster being )
###############################################################################

system_attributes:
    distMPc: 18.3
    name: "FCC047"
    position_angle: 97.69

system_components:

    bh: # black_hole
        parameters:
            m:
                fixed: True
                value: 6.5
                logarithmic: True
                LaTeX: "$M_{BH}$"
            a: # scale length
                fixed: True
                value: 1.e-3  # dot required, renders as str '1e-3' otherwise
                LaTeX: "$a_{BH}$"
        type: "Plummer" # class name
        include: True
        contributes_to_potential: True

    dh: # dark_halo
        parameters:
            c: # NFW Darkmatter concentration
                fixed: True
                value: 10  #10.0
                LaTeX: "$c_{NFW}$"
                par_generator_settings:
                    lo: 1.0
                    hi: 2.0
                    step: 0.1
                    minstep: 0.05
            f: # NFW Darkmatter fraction
                fixed: True
                value: 1.25893
                LaTeX: "$log(M_{200}/M_{star})$"
                logarithmic: False
                par_generator_settings:
                    lo: 0.
                    hi: 3.
                    step: 0.05
                    minstep: 0.01
        type: NFW
        include: True
        contributes_to_potential: True

    stars:
        parameters:
            q: # intrinsic flattening (C/A)
                fixed: True
                value: 0.2 #0.49
                LaTeX: "$q_{min}$"
            p: # intrinsic B/A
                fixed: True
                value: 0.7
                LaTeX: "$p_{min}$"
            u: # sigma_obs / sigma_intrinsic
                fixed: True
                value: 0.9999
                LaTeX: "$u_{min}$"
        type: "TriaxialVisibleComponent" # class name
        mge_pot: "mge4.ecsv"
        mge_lum: "mge4.ecsv"
        include: True
        contributes_to_potential: True
        kinematics: # optional, only specified for components with kinematics
            MUSE: # PLEASE NOTE: DATA NOT PROVIDED WITH DYNAMITE
                weight: 1.0 # weight of kinematics data specified by name
                type: GaussHermite # specifies which object class to create
                hist_width: 10000 #add to kinem #hist_width
                hist_center: 0.0  #add to kinem      #hist_center
                hist_bins: 501    #add to kinem + auto/manual   #bins
                datafile: "gauss_hermite_kins_MUSE.ecsv"  # both discr. & integrated
                aperturefile: "aperture_MUSE.dat" # integrated only
                binfile: "bins_MUSE.dat"          # integrated only
                maskfile: maskfile.dat       # made-up filename
            SINFONI: # PLEASE NOTE: DATA NOT PROVIDED WITH DYNAMITE
                weight: 1.0 # weight of kinematics data specified by name
                type: GaussHermite # specifies which object class to create
                hist_width: 10000 #add to kinem #hist_width
                hist_center: 0.0  #add to kinem      #hist_center 
                hist_bins: 501    #add to kinem + auto/manual   #bins
                datafile: "gauss_hermite_kins_SINFONI.ecsv"  # both discr. & integrated
                aperturefile: "aperture_SINFONI.dat" # integrated only
                binfile: "bins_SINFONI.dat"          # integrated only
                maskfile: maskfile.dat       # made-up filename

system_parameters:
    ml: # M/L
        par_generator_settings:
            lo: 0.8
            hi: 7.5
            step: 1.0
            minstep: 0.5
        fixed: False
        value: 5.5
        LaTeX: "$Y_{r}$"

###############################################################################
# SECTION 2: SETTINGS
# Define other settings e.g. for the orbit library and weight solver
###############################################################################

orblib_settings: # don't put in physical system -> config object
    nE: 6 #21  #5 21
    logrmin: -2.0
    logrmax: 2.2
    nI2: 5 #8        # must be >= 4 8
    nI3: 4 #7 #7
    dithering: 1 #3  #1  3
    #the following values should usually not be changed
    orbital_periods: 200
    sampling: 50000
    starting_orbit: 1
    number_orbits: -1 #-1 --> all orbits
    accuracy: '1.0d-5'
    # the following is intended for development & debugging and should be
    # set to 0 for productive use
    random_seed: 4242 # integer; any value <= 0 results in stochastic seed

weight_solver_settings:
    type: "LegacyWeightSolver"
    nnls_solver: 1
    # type: "NNLS"
    # nnls_solver: 'scipy'
    CRcut: False
    regularisation: 0
    number_GH: 4
    GH_sys_err: '0.0 0.0 0.0 0.0 0.3 0.3 0.6 0.6'
    lum_intr_rel_err: 0.01
    sb_proj_rel_err: 0.02

parameter_space_settings:
    generator_type: "LegacyGridSearch"
    #generator_type: "GridWalk"
    which_chi2: "chi2"
    generator_settings:
        specificsetting: 25
        # For LegacyGridSearch, specify ONE of the following two settings
        #threshold_del_chi2_abs: 0.5  # absolute change in chi2 threshold
        threshold_del_chi2_as_frac_of_sqrt2nobs: 0.1
    stopping_criteria:
        min_delta_chi2_abs : 0.5  # absolute "optimality tolerance"
        #min_delta_chi2_rel : 0.05 # relative "optimality tolerance"
        n_max_mods : 3
        n_max_iter : 10

legacy_settings:
    use_legacy_mode: True
    directory: "default"

io_settings: # paths can be given with or without trailing slash
    input_directory: "FCC047_2kin/FCC047_input/"
    output_directory: "FCC047_2kin/FCC047_output/"
    all_models_file: "all_models.ecsv"

multiprocessing_settings:
    ncpus: 'all_available' # integer or 'all_available'

# end
