#!/bin/bash
#$ -N nNGC62781_54039
#$ -wd /Users/pjethwa/Astro/Science/dynamite/triaxschwarz/model_example_sabine/NGC6278/bh6.00dc1.00f2.00q0.54p0.990u0.9999/
#$ -V 
#$ -o ml0.80/nn.log
#$ -e ml0.80/nn.log
#$ -r yes
## -pe impi4 12 
#$ -m n
#$ -j y
#$ -l h_rt=100:00:00
#$ -hold_jid lNGC62781_54039,bNGC62781_54039
# if the gzipped orbit library exist unzip it
test -e datfil/orblib.dat || bunzip2 -k  datfil/orblib.dat.bz2 
test -e datfil/orblibbox.dat || bunzip2 -k  datfil/orblibbox.dat.bz2
test -e ml0.80/nn_kinem.out || /Users/pjethwa/Astro/Science/dynamite/triaxschwarz/triaxschwarzschild/triaxnnls_CRcut < ml0.80/nn.in 
# if the gzipped orbit library exist unzip it
test -e datfil/orblib.dat || bunzip2 -k  datfil/orblib.dat.bz2 
test -e datfil/orblibbox.dat || bunzip2 -k  datfil/orblibbox.dat.bz2
test -e ml1.80/nn_kinem.out || /Users/pjethwa/Astro/Science/dynamite/triaxschwarz/triaxschwarzschild/triaxnnls_CRcut < ml1.80/nn.in 
# if the gzipped orbit library exist unzip it
test -e datfil/orblib.dat || bunzip2 -k  datfil/orblib.dat.bz2 
test -e datfil/orblibbox.dat || bunzip2 -k  datfil/orblibbox.dat.bz2
test -e ml2.80/nn_kinem.out || /Users/pjethwa/Astro/Science/dynamite/triaxschwarz/triaxschwarzschild/triaxnnls_CRcut < ml2.80/nn.in 
# if the gzipped orbit library exist unzip it
test -e datfil/orblib.dat || bunzip2 -k  datfil/orblib.dat.bz2 
test -e datfil/orblibbox.dat || bunzip2 -k  datfil/orblibbox.dat.bz2
test -e ml3.80/nn_kinem.out || /Users/pjethwa/Astro/Science/dynamite/triaxschwarz/triaxschwarzschild/triaxnnls_CRcut < ml3.80/nn.in 
# if the gzipped orbit library exist unzip it
test -e datfil/orblib.dat || bunzip2 -k  datfil/orblib.dat.bz2 
test -e datfil/orblibbox.dat || bunzip2 -k  datfil/orblibbox.dat.bz2
test -e ml4.80/nn_kinem.out || /Users/pjethwa/Astro/Science/dynamite/triaxschwarz/triaxschwarzschild/triaxnnls_CRcut < ml4.80/nn.in 
# if the gzipped orbit library exist unzip it
test -e datfil/orblib.dat || bunzip2 -k  datfil/orblib.dat.bz2 
test -e datfil/orblibbox.dat || bunzip2 -k  datfil/orblibbox.dat.bz2
test -e ml5.80/nn_kinem.out || /Users/pjethwa/Astro/Science/dynamite/triaxschwarz/triaxschwarzschild/triaxnnls_CRcut < ml5.80/nn.in 
# if the gzipped orbit library exist unzip it
test -e datfil/orblib.dat || bunzip2 -k  datfil/orblib.dat.bz2 
test -e datfil/orblibbox.dat || bunzip2 -k  datfil/orblibbox.dat.bz2
test -e ml6.80/nn_kinem.out || /Users/pjethwa/Astro/Science/dynamite/triaxschwarz/triaxschwarzschild/triaxnnls_CRcut < ml6.80/nn.in 
test -e datfil/orblib.dat.bz2 && rm datfil/orblib.dat
test -e datfil/orblibbox.dat.bz2 && rm datfil/orblibbox.dat
