#!/bin/bash
#$ -N bNGC62781_65339
#$ -l mem_free=1.5G
#$ -wd /Users/pjethwa/Astro/Science/dynamite/triaxschwarz/model_example_sabine/NGC6278/bh6.00dc1.00f2.00q0.54p0.980u0.9999/
#$ -V 
#$ -o datfil/orblibbox.log                 
#$ -e datfil/orblibbox.log              
#$ -r yes
#$ -m n
#$ -j y
#$ -l h_rt=100:00:00
#$ -hold_jid sNGC62781_65339
grep Writing datfil/orblibbox.dat.tmp && rm -f datfil/orblibbox.dat.tmp datfil/orblibbox.dat
/Users/pjethwa/Astro/Science/dynamite/triaxschwarz/triaxschwarzschild/orblib < infil/orblibbox.in 
# if the gzipped orbit library does not exist zip it
test -e datfil/orblibbox.dat.bz2 || bzip2 -k datfil/orblibbox.dat
mv dependid dependid_done
