# Example yaml configuration file for the legacy implementation
# All relevant input is in one file with two sections: SYSTEM and SETTINGS

# Start of yaml document
---
###############################################################################
# SECTION 1 : SYSTEM
# Define the physical system (e.g. the galaxy or globular cluster being )
###############################################################################

system_attributes:
    distMPc: 39.96
    name: "NGC6278"
    position_angle: 97.69

system_components:

    black_hole:
        parameters:
            mass:
                fixed: True
                value: 6.0
                logarithmic: True
                LaTeX: "$M_{BH}$"
            a: # scale length
                fixed: True
                value: 1.e-3  # dot required, renders as str '1e-3' otherwise
                LaTeX: "$a_{BH}$"
        type: "Plummer" # class name
        include: True
        contributes_to_potential: True

    dark_halo:
        parameters:
            dc: # NFW Darkmatter concentration
                fixed: True
                value: 10.0
                LaTeX: "$c_{NFW}$"
            f: # NFW Darkmatter fraction
                fixed: False
                value: 1.0
                LaTeX: "$log(M_{200}/M_{star})$"
                logarithmic: True
                par_generator_settings:
                    lo: 0.
                    hi: 3.
                    step: 0.05
                    minstep: 0.01
        type: NFW
        include: True
        contributes_to_potential: True

    stars:
        parameters:
            q: # intrinsic flattening (C/A)
                fixed: True
                value: 0.54
                LaTeX: "$q_{min}$"
            p: # intrinsic B/A
                fixed: True
                value: 0.99
                LaTeX: "$p_{min}$"
            u: # sigma_obs / sigma_intrinsic
                fixed: True
                value: 0.9999
                LaTeX: "$u_{min}$"
        type: "TriaxialVisibleComponent" # class name
        mge_file: "mge.ecvs"
        include: True
        contributes_to_potential: True
        kinematics: # optional, only specified for components with kinematics
            set1:
                weight: 1.0 # weight of kinematics data specified by name
                type: GaussHermite # specifies which object class to create
                datafile: "gauss_hermite_kins.ecvs"  # both discr. & integrated
                aperturefile: "aperture.dat" # integrated only
                binfile: "bins.dat"          # integrated only

system_parameters: # physical system standalone parameters
    ml: # M/L
        par_generator_settings:
            lo: 0.8
            hi: 7.5
            step: 1.0
            minstep: 0.5
        fixed: False
        value: 3.0
        LaTeX: "$Y_{r}$"

###############################################################################
# SECTION 2: SETTINGS
# Define other settings e.g. for the orbit library and weight solver
###############################################################################

orblib_settings: # don't put in physical system -> config object
    nE: 5
    logrmin: -0.101275
    logrmax: 1.99123
    nI2: 4        # must be >= 4
    nI3: 3
    dithering: 1
    #the following values should usually not be changed
    orbital_periods: 200
    sampling: 50000
    starting_orbit: 1
    number_orbits: -1 #-1 --> all orbits
    accuracy: '1.0d-5'
    hist_vel: '2719.8215332031'
    hist_sigma: '0.0000'  #check what this is
    hist_bins: '205'

weight_solver_settings:
    type: "LegacyWeightSolver"
    setting1: True
    setting2: False
    regularisation: 0
    number_GH: 4
    GH_sys_err: '0.0 0.0 0.0 0.0 0.3 0.3 0.6 0.6'
    lum_intr_rel_err: 0.01
    sb_proj_rel_err: 0.02
    ml_scale_factor: 1.0
    nnls_solver: 1

parameter_space_settings:
    generator_type: "LegacyGridSearch"
    which_chi2: "chi2"
    generator_settings:
        specificsetting: 25
        threshold_del_chi2: 0.5  # LegacyGridSearch setting
    stopping_criteria:
        min_delta_chi2 : 0.5
        n_max_mods : 50
        n_max_iter : 10

legacy_settings:
    use_legacy_mode: True
    directory: "default"

io_settings: # paths can be given with or without trailing slash
    input_directory: "NGC6278_input/"
    output_directory: "NGC6278_output/"
    all_models_file: "all_models.ecsv"

executor_settings:
    type: "Local"     # e.g. Local, Slurm, etc etc
