#!/bin/bash
#$ -N sNGC62781_56125
#$ -l mem_free=1.5G
#$ -wd /Users/pjethwa/Astro/Science/dynamite/triaxschwarz/model_example_sabine/NGC6278/bh6.00dc1.00f2.00q0.58p0.990u0.9999/
#$ -V 
#$ -o datfil/orbstart.log                 
#$ -e datfil/orbstart.log              
#$ -r yes
#$ -m n
#$ -j y
#$ -l h_rt=24:00:00
grep finished datfil/orbstart.dat || /Users/pjethwa/Astro/Science/dynamite/triaxschwarz/triaxschwarzschild/orbitstart < infil/orbstart.in
