.\" @(#)udimen v1.0 11/2000;
.TH udimen 3M "17 Nov 2000"
.SH NAME
UDIMEN \- CUTEr tool to get the number of variables involved.
.SH SYNOPSIS
CALL UDIMEN( INPUT, N )
.SH DESCRIPTION
The UDIMEN subroutine discovers how many variables are involved in
the problem decoded from a SIF file by the script \fIsifdecode\fP.

The problem under consideration
consists in minimizing (or maximizing) an objective function
.EQ
f(x)
.EN
over all
.EQ
x
.EN
\(mo
.EQ
R sup n
.EN
subject to the simple bounds
.EQ
b sup l ~<=~ x ~<=~ b sup u.
.EN
The objective function is group-partially separable.

.LP 
.SH ARGUMENTS
The arguments of UDIMEN are as follows
.TP 5
.B INPUT \fP[in] - integer
the unit number for the decoded data; the unit from which OUTSDIF.d is
read,
.TP
.B N \fP[out] - integer
the number of variables for the problem,
.LP
.SH AUTHORS
I. Bongartz, A.R. Conn, N.I.M. Gould, D. Orban and Ph.L. Toint
.SH "SEE ALSO"
\fICUTEr (and SifDec): A Constrained and Unconstrained Testing
Environment, revisited\fP,
   N.I.M. Gould, D. Orban and Ph.L. Toint,
   ACM TOMS, \fB29\fP:4, pp.373-394, 2003.

\fICUTE: Constrained and Unconstrained Testing Environment\fP,
I. Bongartz, A.R. Conn, N.I.M. Gould and Ph.L. Toint, 
TOMS, \fB21\fP:1, pp.123-160, 1995.

cdimen(3M), sifdecode(1).
