.\" @(#)ugr v1.0 11/2000;
.TH ugr 3M "17 Nov 2000"
.SH NAME
UGR \- CUTEr tool to evaluate gradient.
.SH SYNOPSIS
CALL UGR( N, X, G )
.SH DESCRIPTION
The UGR subroutine evaluates the gradient of the objective function of
the problem decoded from a SIF file by the script \fIsifdecode\fP at the
point X.

The problem under consideration
consists in minimizing (or maximizing) an objective function
.EQ
f(x)
.EN
over all
.EQ
x
.EN
\(mo
.EQ
R sup n
.EN
subject to the simple bounds
.EQ
b sup l ~<=~ x ~<=~ b sup u.
.EN
The objective function is group-partially separable.

.LP 
.SH ARGUMENTS
The arguments of UGR are as follows
.TP 5
.B N \fP[in] - integer
the number of variables for the problem,
.TP
.B X \fP[in] - real/double precision
an array which gives the current estimate of the solution of the
problem,
.TP
.B G \fP[out] - real/double precision
an array which gives the value of the gradient of the objective
function evaluated at X.
.LP
.SH AUTHORS
I. Bongartz, A.R. Conn, N.I.M. Gould, D. Orban and Ph.L. Toint
.SH "SEE ALSO"
\fICUTEr (and SifDec): A Constrained and Unconstrained Testing
Environment, revisited\fP,
   N.I.M. Gould, D. Orban and Ph.L. Toint,
   ACM TOMS, \fB29\fP:4, pp.373-394, 2003.

\fICUTE: Constrained and Unconstrained Testing Environment\fP,
I. Bongartz, A.R. Conn, N.I.M. Gould and Ph.L. Toint, 
TOMS, \fB21\fP:1, pp.123-160, 1995.

cgr(3M), sifdecode(1).
