#!/bin/bash
#$ -N nNGC62781_50192
#$ -wd /Users/pjethwa/Astro/Science/dynamite/triaxschwarz/model_example_sabine/NGC6278/bh6.00dc1.00f2.00q0.50p0.970u0.9999/
#$ -V 
#$ -o ml3.30/nn.log
#$ -e ml3.30/nn.log
#$ -r yes
## -pe impi4 12 
#$ -m n
#$ -j y
#$ -l h_rt=100:00:00
#$ -hold_jid lNGC62781_50192,bNGC62781_50192
# if the gzipped orbit library exist unzip it
test -e datfil/orblib.dat || bunzip2 -k  datfil/orblib.dat.bz2 
test -e datfil/orblibbox.dat || bunzip2 -k  datfil/orblibbox.dat.bz2
test -e ml3.30/nn_kinem.out || /Users/pjethwa/Astro/Science/dynamite/triaxschwarz/triaxschwarzschild/triaxnnls_CRcut < ml3.30/nn.in 
# if the gzipped orbit library exist unzip it
test -e datfil/orblib.dat || bunzip2 -k  datfil/orblib.dat.bz2 
test -e datfil/orblibbox.dat || bunzip2 -k  datfil/orblibbox.dat.bz2
test -e ml4.30/nn_kinem.out || /Users/pjethwa/Astro/Science/dynamite/triaxschwarz/triaxschwarzschild/triaxnnls_CRcut < ml4.30/nn.in 
# if the gzipped orbit library exist unzip it
test -e datfil/orblib.dat || bunzip2 -k  datfil/orblib.dat.bz2 
test -e datfil/orblibbox.dat || bunzip2 -k  datfil/orblibbox.dat.bz2
test -e ml5.30/nn_kinem.out || /Users/pjethwa/Astro/Science/dynamite/triaxschwarz/triaxschwarzschild/triaxnnls_CRcut < ml5.30/nn.in 
test -e datfil/orblib.dat.bz2 && rm datfil/orblib.dat
test -e datfil/orblibbox.dat.bz2 && rm datfil/orblibbox.dat
