# Example yaml configuration file for the legacy implementation
# All relevant input is in one file with two sections: SYSTEM and SETTINGS

# Start of yaml document
---

# SECTION 1
# Data defining the PHYSICAL SYSTEM (e.g., the galaxy)

system_components:

    black_hole:
        parameters:
            mass:
                desc: "log(BHmass)"
                par_generator_settings:
                    lo: 1.0
                    hi: 10.0
                    step: 1.
                    minstep: 0.
                fixed: True
                value: 5.0
                logarithmic: True
                LaTeX: "$M_{BH}$"
                sformat: "6.2f"
            a:
                desc: "scale length"
                fixed: True
                value: 1.e-3  # dot required, renders as str '1e-3' otherwise
                LaTeX: "$a_{BH}$"
                sformat: "7.2f"
        type: "Plummer" # class name
        include: True
        contributes_to_potential: True

    dark_halo:
        parameters:
            dc:
                desc: "NFW Darkmatter concentrion (in log)"
                par_generator_settings:
                    lo: 2.0
                    hi: 4.0
                    step: 1.0
                    minstep: 0.1
                fixed: True
                value: 3.0
                LaTeX: "$log(C)$"
                sformat: "6.2f"
            f:
                desc: "NFW Darkmatter fraction (in log)"
                par_generator_settings:
                    lo: 0.0
                    hi: 2.0
                    step: 0.5
                    minstep: 0.
                logarithmic: True
                fixed: False
                value: 1.0
                LaTeX: "$log(M_{200}/M_{star})$"
                sformat: "6.2f"
        type: NFW
        include: True
        contributes_to_potential: True

    stars:
        parameters:
            q:
                desc: "intrinsic flattening (C/A)"
                par_generator_settings:
                    lo: 0.05
                    hi: 0.99
                    step: 0.04
                    minstep: 0.02
                fixed: True
                value: 0.54
                LaTeX: "$q_{min}$"
                sformat: "6.2f"
            p:
                desc: "intrinsic B/A"
                gpe_parspace_settings:
                    kernel: "to be defined"
                par_generator_settings:
                    lo: 0.99
                    hi: 0.999
                    step: 0.02
                    minstep: 0.01
                fixed: True
                value: 0.99
                LaTeX: "$p_{min}$"
                sformat: "6.3f"
            u:
                desc: "sigma_obs / sigma_intrinsic"
                par_generator_settings:
                    lo: 0.95
                    hi: 1.0
                    step: 0.01
                    minstep: 0.01
                fixed: True
                value: 0.9999
                LaTeX: "$u_{min}$"
                sformat: "7.4f"
        type: "TriaxialVisibleComponent" # class name
        mge_file: "mge.ecvs"
        include: True
        contributes_to_potential: True
        kinematics: # optional, only specified for components with kinematics
            set1:
                weight: 1.0                       # weight of kinematics data specified by name
                type: GaussHermite                # specifies which object class to create
                datafile: "gauss_hermite_kins.ecvs"  # for both discrete and integrated types (actual example file)
                aperturefile: "aperture.dat"      # integrated only (actual example file)
                binfile: "bins.dat"               # integrated only (actual example file)
                maskfile: maskfile.dat          # made-up filename

system_parameters: # these go into the physical system as a standalone parameter (i.e., not one of the components)
    ml:
        desc: "M/L"
        par_generator_settings:
            lo: 4.
            hi: 6.
            step: 1.0
            minstep: 0.5
        fixed: False
        value: 5.
        LaTeX: "$Y_{r}$"
        sformat: "6.2f"

system_attributes:
    distMPc: 39.96
    name: "NGC6278"
    position_angle: 97.69

orblib_settings: # don't put in physical system -> config object
    nE: 2
    logrmin: -0.101275
    logrmax: 1.99123
    nI2: 4
    nI3: 2
    dithering: 1
    #the following values should usually not be changed
    orbital_periods: 200
    sampling: 50000
    starting_orbit: 1
    number_orbits: -1 #-1 --> all orbits
    accuracy: '1.0d-5'
    hist_vel: '2719.8215332031'
    hist_sigma: '0.0000'  #check what this is
    hist_bins: '203'

parameter_space_settings: # don't put in physical system -> settings object
#    generator_type: "gaussian_process_emulator"
    generator_type: "LegacyGridSearch"
#    generator_type: "GridWalk"
    which_chi2: "chi2"
    generator_settings:
        specificsetting: 25
        threshold_del_chi2: 0.5  # LegacyGridSearch setting
    stopping_criteria:
        min_delta_chi2 : 0.5
        n_max_mods : 1000
        n_max_iter : 10

legacy_settings:
    use_legacy_mode: True
    directory: "/Users/pjethwa/Astro/Science/dynamite/triaxschwarz/triaxschwarzschild/"

io_settings: # paths can be given with or without trailing slash
    input_directory: "model_example/NGC6278/input_data"
    output_directory: "model_example/NGC6278/"

weight_solver_settings:
    type: "LegacyWeightSolver"
    setting1: True
    setting2: False
    regularisation: 0
    number_GH: 4
    GH_sys_err: '0.0 0.0 0.0 0.0 0.3 0.3 0.6 0.6'
    lum_intr_rel_err: 0.01
    sb_proj_rel_err: 0.02
    ml_scale_factor: 1.0
    nnls_solver: 1

executor_settings:
    type: "Slurm"     # e.g. Local, Slurm, etc etc
    example_slurm_setting_1: 'I love Slurm!'
    example_slurm_setting_2: 'I love Slurm even more!!'



# end
